<!DOCTYPE html>

<html>

<head>

	<title><?= $page_title ?></title>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<link rel="stylesheet" href="/css/application.css" />

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js"></script>
	<script type="text/javascript" src="/js/application.js"></script>

</head>

<body>

	<?= $yield ?>

</body>

</html>